### ISSUE TITLE
Build on OSX?

### ISSUE THREAD

**Issue by spalger** [ysbaddaden/shards#14]
Would love to try using shards, but I'm unable to get it to build on OSX 10.10.4.

When running `make all` I get:
```sh
$ make all
`which crystal` build -o bin/shards src/shards.cr
ld: library not found for -lyaml
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o bin/shards "/Users/spencer/dev/shards/.crystal/... {hundreds of files} -lyaml -levent -lpcl -lpcre -lgc -lpthread
```

I'm running `Crystal 0.7.4 [42efdbf] (Wed Jun 24 00:55:53 UTC 2015)` installed from https://github.com/manastech/homebrew-crystal with brew, and also have libyaml installed and properly (to brew's standards) linked.

Any ideas what's missing?

**Comment by ysbaddaden** [comment]
Do you have the dev parts of libyaml, by any chance? This is purely a guess since I don't own a Mac...

**Comment by asterite** [comment]
@spalger It works on my machine and all I needed to do is to install `libyaml` from homebrew. Are you sure you have it properly linked?

**Comment by spalger** [comment]
Just to verify ran:
![image](https://cloud.githubusercontent.com/assets/1329312/8565811/cf9df4e8-250d-11e5-8f5a-667e94ae1038.png)

**Comment by spalger** [comment]
Alright, got it! Not sure if this is something I should already have set in my bash_profile (I've never intentionally used gcc) but by setting the library path environment variable it works.

```sh
$ echo $LIBRARY_PATH # empty

$ ls /usr/local/lib/ | grep yaml
libyaml-0.2.dylib
libyaml.a
libyaml.dylib
$ LIBRARY_PATH=/usr/local/lib make all
`which crystal` build -o bin/shards src/shards.cr # success!
```

**Comment by spalger** [comment]
Thanks for the help btw :)

**Comment by ysbaddaden** [comment]
I'm glad you solved this, I wouldn't have been able to help much!
