### ISSUE TITLE
Add support for c libraries.

### ISSUE THREAD

**Issue by technorama** [ysbaddaden/shards#15]
One possible way to add c library support:
1.  A build command (or list of commands) in shard.yml
2.  State tracking and output capture of commands for debugging (similar to rubygems).
3.  Additional library path injection to the crystal build process.  shards.yml could contain additional c library paths.  Minor modification of crystal may be necessary to read the list of additional library paths.

**Comment by ysbaddaden** [comment]
Could you detail your problem and use case before jumping to potential solutions? I'd like to understand what's actually needed beforehand.

It may involve a bunch of problems, like checking for the presence of a library, downloading, compiling, making the lib available to Crystal when linking, etc.

**Comment by technorama** [comment]
Use case #1:

I want to use an existing library but need a few C functions added.   As far as I know the only way to use them is by compiling a library and linking it using the crystal provided c bindings.


Use case #2 (similar to above):

I have a small library in my git repository that must be compiled before crystal build is run.  Crystal c bindings are used to access the library.

**Comment by kostya** [comment]
what if always call `make shard` when install new shard, and if user create that task in Makefile, it would be executed (compile some static c libs or something)

**Comment by ysbaddaden** [comment]
Thanks for the use cases. We could have some hook commands to be run when an action is performed. For example:

```yml
scripts:
  postinstall: "cd ext && make"
```

The most obvious is `postinstall` but there could be others, like pre/post upgrade.

**Comment by ysbaddaden** [comment]
@technorama I just implemented the postinstall script in #19, tell me if it fits your needs.

**Comment by ysbaddaden** [comment]
Closing since #19 got merged.

**Comment by hotty316** [comment]
> One possible way to add c library support:
> 1.  A build command (or list of commands) in shard.yml
> 2.  State tracking and output capture of commands for debugging (similar to rubygems).
> 3.  Additional library path injection to the crystal build process.  shards.yml could contain additional c library paths.  Minor modification of crystal may be necessary to read the list of additional library paths.
>
