### ISSUE TITLE
OSX build fails on Travis

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/shards#24]
It tries to install APT packages, which obviously fails since it's OSX, not Ubuntu Linux.

@jhass @will any idea?

**Comment by jhass** [comment]
I'm not sure there's community support for OS X, so you can follow for now, https://github.com/manastech/crystal/blob/master/.travis.yml, at least roughly. Afaik you should be able to `brew install crystal-lang --with-llvm` or something and skip the libpcl download.

**Comment by will** [comment]
Yeah the addition was https://github.com/travis-ci/travis-build/pull/465/files and it's linux only at the moment
