### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/shards#31]
In order to properly test the lock file behavior , integration tests are required. They would use the compiled shards binary and generate/manipulate different `shard.yml` in different project folders and test the outcome (what dependencies are installed, failures, if it correctly uses the lock file, updates the dependencies and lock file, ...)

refs #12 and #27

**Comment by jhass** [comment]
An interesting tool for this could be [aruba](https://github.com/cucumber/aruba).

**Comment by ysbaddaden** [comment]
Implemented in d02a1db

I didn't need aruba, after all, since I already had almost everything at hand (forging Git repositories, running shell commands, ...)
