### ISSUE TITLE
Use TOML instead of YAML

### ISSUE THREAD

**Issue by emancu** [ysbaddaden/shards#33]
There are few projects using this, including `Cargo`, the Rust's package manager .

An [implementation](https://github.com/manastech/crystal-toml) in Crystal is available too.

**Comment by jhass** [comment]
This has quite extensively been discussed by now in https://github.com/manastech/crystal/issues/220, https://github.com/manastech/crystal/issues/1357 and https://github.com/ysbaddaden/shards/issues/25
