### ISSUE TITLE
Shards for Idiots -- like me.

### ISSUE THREAD

**Issue by reggieb** [ysbaddaden/shards#34]
I'm a ruby developer who wants to write a simple executable and likes the idea of using this as a first Crystal project. I much prefer minitest to spec, so I'd like to use minitest.cr with my new project. It looks like shards should give me the facility to incorporate minitest.cr into my crystal project. 

What I can't work out is how to bring the three elements together: crystal, shards, and minitest. Specifically, how do I install shards locally on my system (I'm using linux - xubuntu), and then how do I get my crystal environment to use it?

Comparing crystal to ruby
====================

It seems to me that shard.yml is the equivalent of Gemfile.yml in ruby

What I'm not sure about is what are the equivalents to:

Installing
-----------
What is the shards equivalent of either:
`sudo apt-get install rubygems`
and/or
`gem install bundler`

Running
----------
What is the shards equivalent to:
`gem install <gem-name>`
or
`bundle install`

I presume the latter is actually what I'm after as the Gemfile.yml to shard.yml usage implies to me that shards is to crystal what bundler is to ruby (rather than rubygems to ruby)

Please forgive me if this seem a little too "Crystal for beginners" but as follower of the sage that is Scott Adams, I know I am just a poor [idiot](http://www.quotationspage.com/quote/32021.html)

**Comment by jhass** [comment]
First of all install Crystal normally, http://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html

You can download a statically compiled 64bit executable from https://github.com/ysbaddaden/shards/releases/tag/v0.4.0

If that doesn't fit your system, download the source tarball from above link and extract it, change into the directory and run `make`. That should produce a binary at `bin/shards`.

Either way make sure that binary is in your `$PATH`, for example by copying it to `/usr/local/bin` or a directory in your `$HOME` that you add to your `$PATH` in your `.bashrc`.

Once that's done go to your project and create a `shard.yml` as seen on the readme or further described in SPEC.md. Then just run `shards install` and you're ready to go.

**Comment by reggieb** [comment]
Thank you @jhass, that was exactly what I was looking for.

**Comment by reggieb** [comment]
Oh! I had to make a further tweak before it all started working. I was getting this error:

`git command failed: git tag --list --no-column`

I fixed that by [updating git to 2.5](https://www.howtoforge.com/install-git-on-ubuntu-13.1)

**Comment by jhass** [comment]
Bad luck I guess, looks like that was added with 1.7.11: https://github.com/git/git/commit/d96e3c150f2b4508f2e7d23ce9183d5b807c2155

**Comment by reggieb** [comment]
Indeed! Mine was 1.7.9.5

**Comment by ysbaddaden** [comment]
There is no such thing as a stupid question. Installation steps are indeed lacking. We'll eventually bundle Shards with Crystal distributions, so this should be simpler.

Thanks for the detailed installation steps @jhass!

Please open an issue about Git < 1.7.11 being unsupported (I'll open one otherwise). Maybe we can fix it, or at least fail with a nice error message, prompting to upgrade Git.

**Comment by jhass** [comment]
I'd say we shouldn't support it, it's supported for more than 3 years by now.

**Comment by reggieb** [comment]
I've open a new issue https://github.com/ysbaddaden/shards/issues/35

I agree with @jhass that it shouldn't be supported, but also with @ysbaddaden that a more meaningful error message would be helpful.

**Comment by reggieb** [comment]
Oh! And what about posting @jhass 's installation steps to this project's wiki?
