### ISSUE TITLE
Error with git version 1.7.9.5

### ISSUE THREAD

**Issue by reggieb** [ysbaddaden/shards#35]
When I tried to run `shards install` after installing shards on an unbuntu system, I got the following error:

    git command failed: git tag --list --no-column

Updating my version of git solved the problem. 

It appears that the --no-column option came in at version 1.7.11 and I was using 1.7.9.5. When I [upgraded git](https://www.howtoforge.com/install-git-on-ubuntu-13.1), the new version was 2.5.

**Comment by ysbaddaden** [comment]
Both Debian Wheezy (LTS) and Ubuntu Precise (LTS) are using older Git versions (1.7.10 or 1.7.9). I'd like to support these distributions, but only it ain't too much work.

Anyway, there should at least be a compatibility version check or a nicer message, prompting to upgrade Git, when a Git command fails.
