### ISSUE TITLE
Dependency free project generates invalid lock

### ISSUE THREAD

**Issue by jhass** [ysbaddaden/shards#37]
Or  "Empty lockfile is invalid", depending on the viewpoint ;)
```
$ echo "name: foo" > shard.yml
$ shards
$ shards
Invalid shard.lock. Please delete it and run install again.
$ cat shard.lock
version: 1.0
shards:

**Comment by ysbaddaden** [comment]
I think there shouldn't be any lock in this case, since there are no dependencies to install.

I just fixed this, thanks for finding this!
