### ISSUE TITLE
Update fails after attempting to resolve dependency that is missing shard spec

### ISSUE THREAD

**Issue by jbye** [ysbaddaden/shards#4]
If you specify a Github dependency that is missing a shard spec (? shard.yml), the dependency resolver will fail as expected:

```
Updating https://github.com/will/crystal-pg.git
cd /home/nitrous/.shards
git clone --mirror --quiet -- 'https://github.com/will/crystal-pg.git' crystal-pg
cd /home/nitrous/.shards/crystal-pg
git tag --list --contains master
cd /home/nitrous/.shards/crystal-pg
git ls-tree -r --full-tree --name-only v0 -- shard.yml
fatal: Not a valid object name v0
git command failed: git ls-tree -r --full-tree --name-only v0 -- shard.yml
```

If you then correct the dependency (such as pointing to another repository, in my case a forked repository that includes a shard spec) and run shards again, the dependency resolver will still fail:

```
Updating https://github.com/jbye/crystal-pg.git
cd /home/nitrous/.shards/crystal-pg
git fetch --all --quiet
cd /home/nitrous/.shards/crystal-pg
git tag --list --no-column
can't resolve crystal-pg (0.1.0)
```

This seems to be caused by the `.shards/crystal-pg` directory created when the resolver ran for the invalid dependency spec. If I remove the `.shards/crystal-pg` directory and re-run shards it succeeds.

**Comment by ysbaddaden** [comment]
I guess we should drop the mirrored repository when the `origin` remote no longer matches the dependency `git_url`.

**Comment by ysbaddaden** [comment]
BTW: shards fakes a `shard.yml` file when it's missing, but I guess I could do better, like setting the version to the current release tag, instead of always setting the version to `0`.

**Comment by jbye** [comment]
In regards to the creation of a fake shard.yml; this does not work for the Github resolver yet?

Running shards using the Github resolver on a project missing a shard.yml yields the following error (which is why I created the fork containing a basic shard.yml):

```
Updating https://github.com/will/crystal-pg.git
fatal: Not a valid object name v0
git command failed: git ls-tree -r --full-tree --name-only v0 -- shard.yml
```

**Comment by ysbaddaden** [comment]
I guess there are no version tags, right? Because it falls back to version `0` and thus tag `v0` which eventually fail the git commands.

I'm not sure what to do in this case: it can't be resilient to the tag missing (because we want this to break in regular cases), or have no default version, which would then use HEAD instead. Maybe the later is better.

**Comment by jbye** [comment]
I was expecting it to default to HEAD. I guess I would prefer being able to refer to HEAD, or even a specific commit (think equivalent to SNAPSHOT dependencies). Not sure if you agree?

**Comment by ysbaddaden** [comment]
You can specify refs using `branch:`, `tag:` or `commit:` since 1d21ea3 (see [diff](https://github.com/ysbaddaden/shards/commit/1d21ea3b66eed302d0a2379ad24fa05de1ac4ef4#diff-e1a9cf629cf2193602a14688f638b449R19)) thought I need to write tests to verify that this behaves correctly when the account has no version tags.

```yaml
dependencies:
  pg:
   github: will/crystal-pg
   commit: abcdefg
```

NOTE: I think we can reference any refs (like HEAD) with `commit:`.

**Comment by jbye** [comment]
Just a note on the ref behaviour you bring up above; it does not behave correctly when the version tag is missing. The same error as reported before is shown

```
Updating https://github.com/datanoise/mongo.cr.git
fatal: Not a valid object name v0
git command failed: git ls-tree -r --full-tree --name-only v0 -- shard.yml
```

for

```
  mongo:
    github: datanoise/mongo.cr
    commit: b718847
```

**Comment by ysbaddaden** [comment]
Specifying a commit, tag or branch should now be working.

**Comment by ysbaddaden** [comment]
And skipping the version or specifying `version: "*"` will now default to install HEAD. Please tell me if it works for you!

All the fixes will quickly generate installation conflicts, but I guess this is inherent to specifying specific refs, over using version numbers and proper dependency requirements: this will always conflict quickly.

**Comment by asterite** [comment]
I had the same issue, I had "webmock" as a dependency with "*" and got `can't resolve webmock (*)`, but now it's working fine :-)

**Comment by jbye** [comment]
After pulling the latest version of shards it works! :)
