### ISSUE TITLE
.shardspec could be useful

### ISSUE THREAD

**Issue by jeromegn** [ysbaddaden/shards#44]
First off: I'm glad this was incorporated into Crystal.

Would it be desirable to add something like Ruby's `.gemspec`? I find that really useful to differentiate gems from projects. Also, it's actually Ruby code which gets evaluated, therefore there's no need to supply the version twice (once in a module's `version.cr` and once in the `shards.yml` file.)

Example:

```crystal
# bson.shardspec

require "./src/bson/version"

Shard::Specification do |spec|
  spec.version = BSON::Version
  # ... other useful stuff once/if there's a registry
end
```

**Comment by jhass** [comment]
Please see the existing extensive discussions at https://github.com/manastech/crystal/issues/220, https://github.com/manastech/crystal/issues/1357 and #25 around the format.

**Comment by jeromegn** [comment]
Ah. I had searched in this repo for something related to that and didn't find anything. I guess I should've looked in the crystal repo.

There's only one real brief mention of the Ruby gemspec in those discussions (well, I didn't read it all, but a quick search found only one result.)

Should I talk about this in manastech/crystal#1357 ?

**Comment by jhass** [comment]
There are several mentions of doing a Crystal based DSL and why that's not really preferable.

**Comment by ysbaddaden** [comment]
Note that the version can be extracted from `shard.yml` at compile time:

```crystal
# src/version.cr
VERSION = {{ `egrep "^version:" "#{ __DIR__ }/shard.yml"`[8 .. -1].stringify.strip }}
```

Not pretty, but doable.

**Comment by jhass** [comment]
We actually could think about compiler support for that once shards ships with it, have compile time access to the entire parsed shard.yml
