### ISSUE TITLE
 ld: warning: directory not found for option '-L/opt/homebrew/lib'

### ISSUE THREAD

**Issue by vjdhama** [ysbaddaden/shards#49]
I get this warning while running tests.
 
Is it because shards dependencies are supposed to be installed in `/opt/homebrew/lib` in osx? If so where can I change it? 

I couldn't figure out where to change it in `Makefile`.

**Comment by jhass** [comment]
Did https://github.com/ysbaddaden/shards/commit/cf7445e40ba9d99b15ecdbf7780cdc4ddaf6404a fix it for you maybe? Try updating.

**Comment by ysbaddaden** [comment]
Actually cba8260a45892de7926b127189f3b871f95310d6 could fix this. The default home-brew lib folder is actually /usr/local/lib (I must update the README).

I just uploaded an OS X binary in https://github.com/ysbaddaden/shards/releases/tag/v0.4.0 so it should be easier to use Shards on OS X

**Comment by vjdhama** [comment]
The problem I think was that I had `/opt/homebrew/lib` in my `$LIBRARY_PATH`. Removing it fixed the issue.

**Comment by ysbaddaden** [comment]
I guess thus is expected if the directory doesn't exist. I updated the README to refe to `/use/local/lib` instead, with a note about using the actual configured place
