### ISSUE TITLE
Tag 'v1.2.3' vs '1.2.3'

### ISSUE THREAD

**Issue by vyp** [ysbaddaden/shards#5]
> Repositories are expected to have version tags, using the v1.2.3 format, this example matching version 1.2.3 of a library.

Minor question, so would this allow a tag named `1.2.3` too or not? If not, I think it should. Any potential problems you know with doing so?

**Comment by ysbaddaden** [comment]
I'm currently expecting tags to be prefixed with `v` to simplify the Git resolver, which assumes `tag = "v#{version}"`. But maybe we could allow both by having `git_refs(version)` check against available tags which one to use.

Also, the `v` prefix is kind of a de-facto convention on GitHub for releases.

**Comment by vyp** [comment]
> Also, the v prefix is kind of a de-facto convention on GitHub for releases.

Ah I feel stupid, so it doesn't work for tags without the v prefix then? Because that's what I've been using (but not in crystal projects yet). Because it's one less key to hit.

In that case I'm okay with closing or postponing this indefinitely because v prefix seems superior. If someone comes asking about this later, it should be easy to implement then anyway. Right now a waste of time.

**Comment by ysbaddaden** [comment]
Oh no, it must work without it for github releases. It's just that many projects in different languages use the `v` prefix (eg: bower packages, rails, ...) in their version tags.

**Comment by vyp** [comment]
Ah right of course, thanks for the clarification.
