### ISSUE TITLE
Should the .shards folder be excluded from the repository

### ISSUE THREAD

**Issue by reggieb** [ysbaddaden/shards#50]
When shards is run, it puts all package data into a .shards folder within the project where it is run.

Should the .shards folder be added to my .gitignore so as to exclude it from my git repository? 

If I pull the code onto another system, I think I'll need to run `shards install` before the associated shards are enabled on the local system - and as this will recreate the .shards folder, is there any point having the .shards folder in the repository.

What is the best strategy?

**Comment by vyp** [comment]
Yes. You can have a look at https://github.com/ysbaddaden/shards/blob/master/.gitignore for more examples. :)

**Comment by ysbaddaden** [comment]
You should add `.shards` and `libs` into your ignore lists. `.shards` is a local cache, and `libs` will be populated as per`shard.lock` —that you should commit.

**Comment by reggieb** [comment]
Excellent. Thank you.
