### ISSUE TITLE
Generate default shard.yml when missing

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/shards#6]
Shards is relatively new and crystal projects don't use it, yet. I hope this will eventually change, but in the meantime shards should do its best to generate default `shard.yml` when libraries don't provide one.

Thus, resolvers should:

- [x] return a minimal `name: <name>\nversion: 0\n`
- [x] parse Projectfile (if present) and extract dependencies
- [x] guess the version, using `GitResolver#version_at(refs)` (note that PathResolver won't be able to guess)

refs #4

**Comment by ysbaddaden** [comment]
Shards is now doing its best to generate a fake `shard.yml` when missing, by extracting the version from git tags, and GitHub dependencies from `Projectfile`.

It's a *best effort* and is likely to work in most cases but not in corner cases. For example, the Projectfile is parsed with regular expressions for strings and not compiled by Crystal, and it will only work for the given cases:

```crystal
deps do
  github "user/project"
  github "user/project", branch: "name"
  github "user/project", "name"
end
```

**Comment by asterite** [comment]
@ysbaddaden This is awesome!! This means that if we decide to change `crystal deps` to use your shards project, the migration will be painless.
