### ISSUE TITLE
`.shards` and `libs` directories are always created

### ISSUE THREAD

**Issue by jessedoyle** [ysbaddaden/shards#61]
I recently noticed that Shards will _always_ create the `.shards` and `libs` directories within the current directory. I don't think this is the desired behaviour.

For example, calling `shards --version` will create both `.shards` and `libs` in the current directory:
```bash
pwd              #=> /Users/jesse/Desktop
ls -a            #=> . .. .DS_Store .localized
shards --version #=> Shards 0.5.0 (2015-9-30)
ls -a            #=> . .. .DS_Store .localized .shards libs
```

I solved the issue on my own local fork of Shards by adding a simple `Shards::Event` module that allows commands to be deferred as such:
```crystal
Event.defer_until(:install, :update) do |event|
  Dir.mkdir_p(CACHE_DIRECTORY) unless Dir.exists?(CACHE_DIRECTORY)
  Dir.mkdir_p(INSTALL_PATH) unless Dir.exists?(INSTALL_PATH)
end
```

and:
```crystal
# in src/commands/install.cr#initialize
Event.announce(:install)
```

I also think a simple event mechanism may be useful in other situations across the Shards codebase.

Does this approach seem reasonable to you? I'll submit a PR if you agree with it.

**Comment by ysbaddaden** [comment]
Definitely a bug. A `Dir.mkdir_p` should be enough thought. I don't think we need deferred events for this, but maybe for updating Git caches only when required.

**Comment by jessedoyle** [comment]
Thanks!
