### ISSUE TITLE
New command: init

### ISSUE THREAD

**Issue by jhass** [ysbaddaden/shards#64]
`crystal init` creates a whole project structure. That's not always wanted, especially when turning an existing project into a shard. `shards init` should write a simple example `shard.yml` to the current git repositories root.

**Comment by ysbaddaden** [comment]
It could also ask for a few questions, like bower or npm does.

**Comment by ysbaddaden** [comment]
A preliminary version of the command is now available. We may improve it later.

**Comment by jhass** [comment]
Thanks!
