### ISSUE TITLE
Makefile not copied to libs

### ISSUE THREAD

**Issue by kostya** [ysbaddaden/shards#73]
I am trying postinstall script (make something), but shards not coping Makefile to libs, so its failed.

**Comment by ysbaddaden** [comment]
There was a proposal for Crystal to change the search path for `require "foo"` to add `libs/foo/src/foo.cr`. This would play better with Shards, where we could just install the dependency as-is instead of requiring a `src` folder and copying a few more files.

**Comment by asterite** [comment]
@ysbaddaden We could change that logic right now and have if for the next version of Crystal. Should I do it? Seems pretty simple to implement :-)

**Comment by ysbaddaden** [comment]
I'll have a look. If it's simple, let's dive in the compiler :)

**Comment by asterite** [comment]
If you want to do it, you should look at these :-)

https://github.com/manastech/crystal/blob/master/src/compiler/crystal/crystal_path.cr
https://github.com/manastech/crystal/blob/master/spec/compiler/crystal_path/crystal_path_spec.cr

The code is a bit messy right now because we didn't have `Dir.glob` when it was written.

**Comment by ysbaddaden** [comment]
@kostya there is a workaround:

1. having a Makefile in `src/ext` whose sole purpose it to download & build the C library;
2. make sure `@Link` looks like `@[Link(ldflags: "-L#{__DIR__}/ext -lcmark")]` so the linker is specified the correct folder when looking for the library;
3. add a `postinstall: cd ext && make` script to `shard.yml`;
4. add a `cd src/ext && make` to the main Makefile, for development purposes.

See https://github.com/ysbaddaden/crystal-cmark for a working sample.

**Comment by kostya** [comment]
also worked already here https://github.com/kostya/http_parser.cr
