### ISSUE TITLE
bad autocomplete

### ISSUE THREAD

**Issue by kostya** [ysbaddaden/shards#74]
for ruby
```
$ vim Ge[Tab]
```

for crystal
```
$ vim sh[Tab]y[Tab]
```

because shard.lock and shard.yml files, i think this is important

**Comment by ysbaddaden** [comment]
Yes, unfortunately. But what do you propose?

Cargo has the same "problem" (`Cargo.toml` & `Cargo.lock`) by the way.

**Comment by kostya** [comment]
shard.lock is metafile, not need to, not need to autocomplete, what about `.shard.lock`

**Comment by ysbaddaden** [comment]
I agree this is a little cumbersome to type an extra `<y>` and `<tab>` but I can live with it. I'm not changing my shards so often that it becomes painful (and yes I _do_ code using vim in a terminal all day long).
