### ISSUE TITLE
Github login with personal access token

### ISSUE THREAD

**Issue by ScotterC** [ysbaddaden/shards#79]
Can you point me to the code related to authenticating with github? I have 2 factor authentication and as far as I can tell entering personal access tokens for the password field aren't working

```
 ~/code/crystal-world : shards install
Updating https://github.com/kemalcr/kemal.cr.git
Username for 'https://github.com': ScotterC
Password for 'https://ScotterC@github.com': {entered personal access toke}
Failed to clone https://github.com/kemalcr/kemal.cr.git
```

Shards 0.5.3 (2015-10-30)
Crystal 0.9.1

**Comment by ScotterC** [comment]
Exploring a bit more:

```
 ~/code/crystal-world : shards install -v
Updating https://github.com/kemalcr/kemal.cr.git
git clone --mirror --quiet -- 'https://github.com/kemalcr/kemal.cr.git' kemal
Username for 'https://github.com': ScotterC
Password for 'https://ScotterC@github.com':
Failed to clone https://github.com/kemalcr/kemal.cr.git
```

```
git clone --mirror --quiet -- 'https://github.com/kemalcr/kemal.cr.git' kemal
```
fails the same way

replacing with ssh url succeeds:
```
git clone --mirror --quiet -- 'git@github.com:kemalcr/kemal.git' kemal
```


What's the advantage of https urls over ssh?

**Comment by ysbaddaden** [comment]
Please use `git: git@github.com:user/repo.git` instead of `github: user/repo` when cloning private libraries. The github resolver just rewrites the URL then the git resolver does all the job. It's only meant to cleanup dependencies in `shard.yml` for public libraries.
