### ISSUE TITLE
Development dependencies

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/shards#8]
Event thought shards won't distribute end-user software, contributing to a library and using a library are different matters, and don't necessarily require the same set of libraries. We should thus have development dependencies along with the regular dependencies.

The development dependencies would only be searched and installed for the current project. Shards shall only ever install nested dependencies only.

**Comment by Mparaiso** [comment]
Ideally there should be some kind of group system like in gem files 

# global deps
group :test do
# test dep
end

obviously with a yaml syntaxt

then one can call your package manager like that

shards --with test 

What do you think ?    ...

**Comment by ysbaddaden** [comment]
This is an interesting approach, and optional groups in the latest Ruby Bundler are very nice, indeed.

Any hash under `dependencies` would be an optional group, targeting only the main shard and not applying to its dependencies; with `development` being activated by default.

Sounds good!

**Comment by ysbaddaden** [comment]
This was implemented in 01f10c9 with tests in c9ef137
