### ISSUE TITLE
Unable to run shards install

### ISSUE THREAD

**Issue by djberg96** [ysbaddaden/shards#82]
New to Crystal, and am trying to use shards, but I'm having an issue:
    
    >crystal -v
    Crystal 0.9.1 (Fri Oct 30 13:49:50 UTC 2015)

    >shards install
    Missing shard.yml. Please run 'shards install'

Is there a stock shard.yml I can use? If so, where do I put it?

**Comment by asterite** [comment]
You can use `crystal init lib some_lib` and it will generate an empty shard.yml file. Alternatively there are some docs here: https://github.com/ysbaddaden/shards

**Comment by djberg96** [comment]
@asterite I was trying to perform the analogue of a gem search -r, but I guess there's no central repo. I didn't realize it was only per-project at the moment.

**Comment by asterite** [comment]
@djberg96 Oh, I see. There's a website that lists the few that are out there on github: http://crystalshards.herokuapp.com/

**Comment by ysbaddaden** [comment]
Registry is being worked on :-)

**Comment by asterite** [comment]
:heart_eyes_cat:
