### ISSUE TITLE
libs folder has libraries from outdated `shards.yml`.

### ISSUE THREAD

**Issue by vjdhama** [ysbaddaden/shards#83]
I created a crystal lib and added a development_dependency in `shards.yml`. Now I removed that dependency, but the fetched lib still stays inside libs folder of the project. Is this expected behavior?

**Comment by luislavena** [comment]
@vjdhama I believe there is no purge of removed libraries unless manual removal is done (at this time).

Hope that helps.

**Comment by luislavena** [comment]
See #57

**Comment by ysbaddaden** [comment]
Yes, this is the expected behavior. I actually follow other package managers like Bower or Bundler that don't clean up until they're told so.

**Comment by ysbaddaden** [comment]
Duplicate of #78
